name = "lin-fan-api"
compatibility_date = "2023-12-01"
account_id = "644cca80ced0666be85479869a4f17a8"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "lin-fan-db"
database_id = "da046e95-77d5-476b-adb2-39058279b5f5"
migrations_dir = "../../packages/db/drizzle"
